### ISSUE TITLE
Weird Lighting Glitches

### ISSUE THREAD

**Issue by supsm** [jellysquid3/phosphor-fabric#33] opened 2020-12-26 18:00 UTC
My server is running phosphor with some other mods, and I've noticed that there are strange lighting glitches in some places. This didn't happen when I first arrived here, but when I came back the lighting became strange. It looks like something is blocking the light above, but there isn't anything.
![2020-12-26_09 55 33](https://user-images.githubusercontent.com/60897356/103156755-fce17a80-4760-11eb-8753-43e4746736bc.png)

I'm not sure if this has anything to do with it, but I'm running a different (0.6.0) version of phosphor on my client (0.7.0 on server), as well as canvas (sorry lol)

**Comment by PhiProven** [comment] 2020-12-27 09:53
Phosphor servers should work well with Vanilla clients (or older versions of Phosphor) and vice versa. Unfortunately, I'm unable to reprodue any similar kind of glitches. Can you provide some additional information?
* Which mods are running on the server and client
* Which version of MC do server and client use
* Was the world generated with Phosphor 0.7.0 or an older version/Vanilla

Furthermore, when encountering such a glitch, please plant a sapling in the dark chunks and see if it grows (or place an ice block and see if it melts). That would help to figure out whether the issue is serverside or clientside. (Given that no mobs seem to spawn, this looks like a clientside issue)

**Comment by supsm** [comment] 2020-12-28 18:26
Client mods:
    appleskin, bedrockify, betterpingdisplay, canvas, connectedblocktextures, fabric api, carpet, lambdynamiclights, light overlay, litematica, lithium, malilib, minihud, modmenu, okzoomer, phosphor, replaymod, resourceopts, shulkerboxtooltip, simple rpc, tweakeroo, xaero's minimap, xaero's worldmap

Server mods: blcdisabler, carpet extra, dimthread, fabric api, carpet, fast furnace, krypton, lithium, phosphor, tic-tacs

Server and client are both running on 1.16.4
World was generated with phosphor 0.6.0
I haven't encountered this issue since then (I probably need to fly a few hundred blocks), but I'll do the test when that happens.

**Comment by PhiProven** [comment] 2020-12-28 18:34
Which version of tic-tacs? The current release (0.1.2) is not compatible with Phosphor 0.7.0.
This has been fixed in the dev branch of tic-tacs, but is not yet included in any official release. For the time being, you can however compile the dev version of tic-tacs yourself.

**Comment by supsm** [comment] 2020-12-28 18:37
Ah, ok. That was probably the issue then.

**Comment by supsm** [comment] 2021-01-19 21:36
It was working fine, but starting today I found that there were more lighting glitches. This time, I can verify that the sky light level is actually lower, and mobs were spawning.
![2021-01-19_09 07 56](https://user-images.githubusercontent.com/60897356/105097407-5e91bd80-5a5d-11eb-9091-4281cfc2361f.png)

**Comment by TheGreatCatAdorer** [comment] 2021-01-22 15:21
I have also experienced this issue server-side.
Mods: REI, Carpet-fabric, YUNG's Better Caves, Simplex Terrain, Fabric API, Xaero's Minimap, Mo' Structures, Sodium, Lithium, Hwyla, Logical Zoom, Connected Block Textures, Phosphor 0.7.0, RER, Appleskin, Carpet-auto-crafting-table.  
The issue was observed in single-player and after my character died.

**Comment by supsm** [comment] 2021-01-25 19:30
The patterns seem to change instead of being the same. When I came through the portal earlier, around half of it was black (including the savanna plateau you see in the previous screenshot). When I flew away and came back, pretty much everything was black, with a few places that are a bit brighter (but they don't look like they are completely light either).

**Comment by supsm** [comment] 2021-01-25 19:49
I've switched back to Phosphor 0.6.0, and the issue still persists. However, There were less dark spots, and returning after flying away didn't change the dark spots much.

**Comment by supsm** [comment] 2021-01-25 19:59
After removing phosphor, this still happens. They were in the same patterns as with phosphor 0.6.0, indicating that something changed in phosphor 0.7.0. For this reason, I will leave this issue open.

**Comment by supsm** [comment] 2021-01-27 22:39
It seems that chunks generated with phosphor are glitched, but chunks generated after I removed phosphor are fine. Is there any way to fix this?

**Comment by TheRobified** [comment] 2021-01-28 02:29
> It seems that chunks generated with phosphor are glitched, but chunks generated after I removed phosphor are fine. Is there any way to fix this?

Have you tried doing --forceUpgrade in the JVM arguments? It should force the light engine to recalculate light levels in all chunks - this can take awhile.

**Comment by LucilleTea** [comment] 2021-01-28 02:32
You need `--forceUpgrade --eraseCache` to reset light.

**Comment by PhiProven** [comment] 2021-02-12 05:34
Not sure if the bugfixes in 0.7.1 also fix this issue here.
Feel free to reopen if the issue still occurs with Phosphor 0.7.1 (after optimizing old worlds once), preferably with no other mods installed.

**Closed as completed by PhiProven** 2021-02-12 05:34 UTC
Labels: bug
