### ISSUE TITLE
Not compatible with fabric 1.19.3

### ISSUE THREAD

**Issue by ghost** [jellysquid3/phosphor-fabric#86] opened 2022-12-13 16:51 UTC
Crashes when starting up minecraft fabric 1.19.3 with this phosphor version.

**Comment by PhiProven** [comment] 2022-12-14 14:29
Please post the full crash report.

**Comment by bagong** [comment] 2022-12-26 11:23
Same here... Win-11 64 bit, Temurin Java 19.01 Latest Fabric, Lithium, Sodium and (not) Phosphor:
``````
MultiMC version: 0.6.16-3431


Launched instance in online mode

authserver.mojang.com resolves to:
    [143.204.203.46, 143.204.203.50, 143.204.203.41, 143.204.203.55]

session.minecraft.net resolves to:
    [35.153.153.200, 34.197.32.8, 100.24.172.95]

textures.minecraft.net resolves to:
    [2620:1ec:4e:1::60, 2620:1ec:4f:1::60, 13.107.237.60, 13.107.238.60]

api.mojang.com resolves to:
    [13.32.27.50, 13.32.27.94, 13.32.27.85, 13.32.27.112]


Minecraft folder is:
C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/instances/Fabric/.minecraft


Java path is:
C:/Program Files/Eclipse Adoptium/jdk-19.0.1.10-hotspot/bin/javaw.exe


Checking Java version...
Java is version 19.0.1, using 64-bit architecture, from Eclipse Adoptium.


Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/instances/Fabric/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/com/mojang/authlib/3.16.29/authlib-3.16.29.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/com/mojang/javabridge/2.0.25/javabridge-2.0.25.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/com/mojang/text2speech/1.13.9/text2speech-1.13.9.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/net/fabricmc/intermediary/1.19.3/intermediary-1.19.3.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/ow2/asm/asm/9.4/asm-9.4.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/ow2/asm/asm-analysis/9.4/asm-analysis-9.4.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/ow2/asm/asm-commons/9.4/asm-commons-9.4.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/ow2/asm/asm-tree/9.4/asm-tree-9.4.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/ow2/asm/asm-util/9.4/asm-util-9.4.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/net/fabricmc/fabric-loader/0.14.12/fabric-loader-0.14.12.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/com/mojang/minecraft/1.19.3/minecraft-1.19.3-client.jar

Native libraries:
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-windows.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-windows.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-windows.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-windows.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-windows.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-windows.jar
  C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-windows.jar

Mods:
  [✔️] lithium-fabric-mc1.19.3-0.10.4
  [✔️] phosphor-fabric-mc1.19.x-0.8.1-dev
  [✔️] sodium-fabric-mc1.19.3-0.4.6+build.20

Params:
  --username  --version 1.19.3 --gameDir C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/instances/Fabric/.minecraft --assetsDir C:/ProgramData/chocolatey/lib/multimc/tools/MultiMC/assets --assetIndex 2 --uuid  --accessToken  --userType  --versionType release

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 18852


Using onesix launcher.

[12:20:30] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.12
[12:20:31] [main/INFO]: Loading 10 mods:
	- fabric-api-base 0.4.19+8d1895cf72 via sodium
	- fabric-rendering-data-attachment-v1 0.3.23+48349a3f72 via sodium
	- fabric-rendering-fluids-v1 3.0.16+3067f46372 via sodium
	- fabric-resource-loader-v0 0.10.2+f6c919d672 via sodium
	- fabricloader 0.14.12
	- java 19
	- lithium 0.10.4
	- minecraft 1.19.3
	- phosphor 0.8.1
	- sodium 0.4.6+build.20
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Failed to read accessWidener file from mod phosphor
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:441)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 5 more
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:439)
	... 9 more
Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
````

**Comment by OpenBagTwo** [comment] 2022-12-29 19:09
Been working fine for me with Quilt Loader 0.17.8.

**Comment by jellysquid3** [comment] 2023-06-25 00:50
Closing as this isn't a problem with Phosphor, but rather your environment.

**Closed as not planned by jellysquid3** 2023-06-25 00:50 UTC
