### ISSUE TITLE
Mod Compatibility with Distant Horizons

### ISSUE THREAD

**Issue by Jakobabs** [jellysquid3/phosphor-fabric#81] opened 2022-05-24 17:33 UTC
When using both this mod and Distant Horizons, generating fake chunks with "Enable Distant Generation = true" and "Light Generation Mode = fancy" results in the generated fake chunks black. Switching "Light Generation Mode = fast" uses the Distant Horizons mod's own light engine and fixes the issue but uses a lower quality light engine. As phosphor replaces the Minecraft light engine, When using the fancy option, it uses phosphor's engine causing the black fake chunks

**Comment by PhiProven** [comment] 2022-05-24 22:02
Phosphor adds logic to the `FEATURES` chunk generation stage in [MixinChunkStatus](https://github.com/CaffeineMC/phosphor-fabric/blob/1.18.x/dev/src/main/java/net/caffeinemc/phosphor/mixin/chunk/MixinChunkStatus.java). As far as I can tell, `Distant Horizons` overrides that part of MC code in [StepFeatures](https://gitlab.com/jeseibel/minecraft-lod-mod/-/blob/main/common/src/main/java/com/seibel/lod/common/wrappers/worldGeneration/step/StepFeatures.java), rendering Phosphor's Mixin ineffective. This needs to be addressed in `Distant Horizons` by calling Phosphor's `ServerLightingProvider.setupLightmaps(Chunk chunk)` hook.

**Comment by PhiProven** [comment] 2022-05-27 12:35
Closing this as it is on `Distant Horizon`'s end to fix. For reference, the issue is tracked in https://gitlab.com/jeseibel/minecraft-lod-mod/-/issues/308.
Let me know in case any adjustments from our side are needed.

**Closed as completed by PhiProven** 2022-05-27 12:35 UTC
