### ISSUE TITLE
Phosphor update?

### ISSUE THREAD

**Issue by IISzalonnaII** [jellysquid3/phosphor-fabric#64] opened 2021-08-20 14:24 UTC
Where is the Phosphor update to 1.17.1? Lithium, Sodium and Hydrogen are updated to 1.17.1.

**Comment by K0-RR** [comment] 2021-08-20 16:50
Duplicate of https://github.com/CaffeineMC/phosphor-fabric/issues/54, https://github.com/CaffeineMC/phosphor-fabric/issues/56, https://github.com/CaffeineMC/phosphor-fabric/issues/57, https://github.com/CaffeineMC/phosphor-fabric/issues/58, https://github.com/CaffeineMC/phosphor-fabric/issues/61.

**Comment by fenrave** [comment] 2021-08-25 14:51
https://github.com/CaffeineMC/phosphor-fabric/pull/59 

They're working on it. Feel free to try and help them out if you want to push this along.

**Closed as completed** 2021-08-26 03:53 UTC
