### ISSUE TITLE
Dark chunks still occur with Phosphor 7.1

### ISSUE THREAD

**Issue by CalXee** [jellysquid3/phosphor-fabric#49] opened 2021-03-27 18:52 UTC
The dark chunk issue can still be reproduced in version 7.1 by entering a nether portal and repeating that for a long time. This is a rare occurrence but one nonetheless.

https://www.youtube.com/watch?v=mGDKO5sPvdQ
[profile-results-2021-03-27_14.41.33.txt](https://github.com/CaffeineMC/phosphor-fabric/files/6216206/profile-results-2021-03-27_14.41.33.txt)
[debug-report-2021-03-27_14.41.43.zip](https://github.com/CaffeineMC/phosphor-fabric/files/6216207/debug-report-2021-03-27_14.41.43.zip)

Note in the attached video, I was using standalone Phosphor 7.1 with NO OTHER MODS, not even Modmenu or Fabric API.

**Comment by DragonEggBedrockBreaking** [comment] 2021-03-27 18:57
> Note in the attached video, I was using standalone Phosphor 7.1.

By that, do you mean that you were using *only* Phosphor 0.7.1, and no other mods?

**Comment by BBloom81** [comment] 2021-04-09 20:29
Thank you for showing this video, I've been going crazy trying to figure out what was constantly causing lighting glitches in my chunks.  I'd come back from the Nether and have 4 more straight black chunks... was getting to the point I'd be spending most of my game time trying to fix the lighting issues.
I'm just gonna remove all of this devs mods. They almost never get updated and cause major issues when something does go wrong.  It's a same, they really do help performance, but it's too steep a cost, especially with no/very little attention given to these major bugs.

**Comment by mrmangohands** [comment] 2021-04-09 21:54
> Thank you for showing this video, I've been going crazy trying to figure out what was constantly causing lighting glitches in my chunks. I'd come back from the Nether and have 4 more straight black chunks... was getting to the point I'd be spending most of my game time trying to fix the lighting issues.
> I'm just gonna remove all of this devs mods. They almost never get updated and cause major issues when something does go wrong. It's a same, they really do help performance, but it's too steep a cost, especially with no/very little attention given to these major bugs.

Frankly this is the only known issue of this severity in either Lithium or Phosphor at the moment, and until an hour ago we'd had a single report of it in the two months this release has been out. Generally we get to such issues quite quickly, but PhiPro has not had much time available lately, and the last issue of this variety took several of us *many* hours to debug, and additionally we can't even be sure whether these are actually phosphor issues or rather vanilla bugs that're usually masked until we've found the root cause.

**Comment by PhiProven** [comment] 2021-04-12 15:34
I have fixed one possible cause for this issue in 7b32057.
However, due to the irreproducibility of this bug, I can't tell whether this actually was the cause or not.
So let me know if you still encounter the issue with this build. Please relight the world once when updating (or create a new world) in order to remove all previous glitches.

**Comment by BBloom81** [comment] 2021-04-12 21:28
> I have fixed one possible cause for this issue in [7b32057](https://github.com/CaffeineMC/phosphor-fabric/commit/7b32057e808127fe56486e77a32be7c44120ca9b).
> However, due to the irreproducibility of this bug, I can't tell whether this actually was the cause or not.
> So let me know if you still encounter the issue with this build. Please relight the world once when updating (or create a new world) in order to remove all previous glitches.

I've been relighting chunks manually thanks to this. I love how you suggest to make a new world, as if all the time spent in the world and things built should just be forgotten because of your glitchy mod.
That's the kind of response right there that makes me happy I'm not running anything JellySquid has had their hands on and never will again.  Piss poor, plain and simple.

By the way, I'm very happy to report I've not had a single new lighting issue since removing your mods.  It's been wonderful.

**Comment by coderbot16** [comment] 2021-04-12 22:00
> I've been relighting chunks manually thanks to this. I love how you suggest to make a new world, as if all the time spent in the world and things built should just be forgotten because of your glitchy mod.

It's trivial to relight the entirety an existing world through the Optimize World dialog. Creating a new world was simply a suggestion in the case that users were creating temporary test worlds or similar, such as what CalXee was doing.

> That's the kind of response right there that makes me happy I'm not running anything JellySquid has had their hands on and never will again. Piss poor, plain and simple.

Tell us, how would you have handled this better?

> By the way, I'm very happy to report I've not had a single new lighting issue since removing your mods. It's been wonderful.

Feel free to not use the mods, nobody is forcing you to do so. But I don't see what you intend to accomplish through being a dick on the issue tracker.

**Comment by mrmangohands** [comment] 2021-04-12 22:01
@BBloom81 you can relight chunks in your existing world by launching the server with --forceUpgrade --eraseCache. If you're in single player it's edit -> optimize world -> erase cached data.

**Comment by K0-RR** [comment] 2021-04-12 22:04
Sorry for the ping, I should go to bed if I can't even read...

**Comment by CalXee** [comment] 2021-04-12 22:26
I believe it's only ethical and productive to use issue trackers to bring issues to light and get them fixed with the intention of making the mod better; not to insult the mod or it's developers.

**Comment by BBloom81** [comment] 2021-04-13 00:37
> I believe it's only ethical and productive to use issue trackers to bring issues to light and get them fixed with the intention of making the mod better; not to insult the mod or it's developers.

1: I don't get pissy about first time problems, but I certainly do when a dev claims to have fixed an issue, so you go through a bunch of crap to supposedly update your world per what the dev suggests. Then the problem not only continues, but does so at an accelerated rate, but the dev fixed the issue so it must not be their mod... oh wait, it IS their mod, they did not fix the issue, they just claimed to.  How many issues with their mods that they mark "exposes vanilla bug" do you think are legit? I'm seriously questioning how many are legit and how many are the devs just not knowing how to fix what they're breaking.

2. It's funny you use the word "ethical".  I've been nothing but upfront and honest, I've been ethical.  Have the devs been ethical in reporting a bug fixed that was actually made worse and hiding their heads until someone caught their mod doing it on video?  Not exactly.

3. No sure where I've insulted anyone. I simply stated that these mods have major issues, as with what they do, even a minor issue is a major one that can ruin someone's world. I've read countless posts on git and reddit from JellySquid crying because someone is running into issues with their mod and it's just not fair that everything they touch is not turning to gold and it's so mean and rude that people are pointing out the issues and that the supposed performance gains with some of them are crazy overexaggerated. 

If you can't tell, I'm pissed and as far as I'm concerned, rightly so.  Again, we were told this issue was fixed. I spent weeks thinking I was running into vanilla bugs, trying to figure out a way to save my, so-I-thought, corrupting/dying world, only to find out it's all due to a dev that claimed their stuff was fixed then hid their head in the sand.
When someone can give me the 100+ hours I spent fixing chunks, researching ways to stop this, trying different types of servers in hopes of using plugins to stop it... then I'll stop being pissed.  Sound good?

**Comment by DragonEggBedrockBreaking** [comment] 2021-04-13 09:13
> I certainly do when a dev claims to have fixed an issue, so you go through a bunch of crap to supposedly update your world per what the dev suggests. Then the problem not only continues, but does so at an accelerated rate, but the dev fixed the issue so it must not be their mod... oh wait, it IS their mod, they did not fix the issue, they just claimed to.

They have not claimed to fix an issue, as the issue report remains open. They were asking the issue report creator to test whether it is fixed, after an extensive conversation on discord. You were never asked yourself to do anything other than have basic common sense.

> How many issues with their mods that they mark "exposes vanilla bug" do you think are legit? I'm seriously questioning how many are legit and how many are the devs just not knowing how to fix what they're breaking.

You seem to have so little technical knowledge of the mod that I am questioning whether you even tested the correct builds. Phosphor exposes a lot of vanilla bugs that are concealed by vanilla. The devs of this mod are experienced and definitely know more than you.

> I've been ethical.

How ethical is disrupting a mod’s issue report section because you are pissed for little reason?

> Have the devs been ethical in reporting a bug fixed that was actually made worse and hiding their heads until someone caught their mod doing it on video?  Not exactly.

They didn’t know that this issue existed. That’s what issue reports are for. If they wanted to hide anything, they could disable issues and make this mod closed source. Instead, they are openly putting effort into fixing it. Again, common sense.

> 2. No sure where I've insulted anyone. I simply stated that these mods have major issues, as with what they do, even a minor issue is a major one that can ruin someone's world. I've read countless posts on git and reddit from JellySquid crying because someone is running into issues with their mod and it's just not fair that everything they touch is not turning to gold and it's so mean and rude that people are pointing out the issues and that the supposed performance gains with some of them are crazy overexaggerated.

1) They are not over exaggerated, it is just that some gain more performance than others, e.g. if you get 150fps in vanilla and 600 with sodium, then another person who gets 50fps in vanilla can’t expect 600 with sodium, it’s basic maths.

2) Sodium’s issues are being quickly fixed, lithium has no major issues, and this is the only major issue in phosphor. Seems like *you* are the one over exaggerating.

> If you can't tell, I'm pissed and as far as I'm concerned, rightly so. Again, we were told this issue was fixed. I spent weeks thinking I was running into vanilla bugs, trying to figure out a way to save my, so-I-thought, corrupting/dying world, only to find out it's all due to a dev that claimed their stuff was fixed then hid their head in the sand.

Again, give me any evidence that a dev claimed it is fixed. See, the issue report is **open**.

> When someone can give me the 100+ hours I spent fixing chunks, researching ways to stop this, trying different types of servers in hopes of using plugins to stop it... then I'll stop being pissed. Sound good?

100+ hours? From what you have said before, there is no way you spent this long. I’m guessing 20 mins fixing it and 5 mins ranting on GitHub? Also, the devs are the ones spending hours. Remember that you are getting this for free. Just stop using the mods. Nobody cares. So what if your lack of common sense means you have to type a rant on GitHub? Deal with it. There are thousands of people using these mods, and these mods are being developed for free.

Don’t bother typing one of your “valuable” responses, it’s just spam at this point.

**Comment by BBloom81** [comment] 2021-04-13 11:13
> > I certainly do when a dev claims to have fixed an issue, so you go through a bunch of crap to supposedly update your world per what the dev suggests. Then the problem not only continues, but does so at an accelerated rate, but the dev fixed the issue so it must not be their mod... oh wait, it IS their mod, they did not fix the issue, they just claimed to.
> 
> They have not claimed to fix an issue, as the issue report remains open. They were asking the issue report creator to test whether it is fixed, after an extensive conversation on discord. You were never asked yourself to do anything other than have basic common sense.
> 
> > How many issues with their mods that they mark "exposes vanilla bug" do you think are legit? I'm seriously questioning how many are legit and how many are the devs just not knowing how to fix what they're breaking.
> 
> You seem to have so little technical knowledge of the mod that I am questioning whether you even tested the correct builds. Phosphor exposes a lot of vanilla bugs that are concealed by vanilla. The devs of this mod are experienced and definitely know more than you.
> 
> > I've been ethical.
> 
> How ethical is disrupting a mod’s issue report section because you are pissed for little reason?
> 
> > Have the devs been ethical in reporting a bug fixed that was actually made worse and hiding their heads until someone caught their mod doing it on video?  Not exactly.
> 
> They didn’t know that this issue existed. That’s what issue reports are for. If they wanted to hide anything, they could disable issues and make this mod closed source. Instead, they are openly putting effort into fixing it. Again, common sense.
> 
> > 1. No sure where I've insulted anyone. I simply stated that these mods have major issues, as with what they do, even a minor issue is a major one that can ruin someone's world. I've read countless posts on git and reddit from JellySquid crying because someone is running into issues with their mod and it's just not fair that everything they touch is not turning to gold and it's so mean and rude that people are pointing out the issues and that the supposed performance gains with some of them are crazy overexaggerated.
> 
> 1. They are not over exaggerated, it is just that some gain more performance than others, e.g. if you get 150fps in vanilla and 600 with sodium, then another person who gets 50fps in vanilla can’t expect 600 with sodium, it’s basic maths.
> 2. Sodium’s issues are being quickly fixed, lithium has no major issues, and this is the only major issue in phosphor. Seems like _you_ are the one over exaggerating.
> 
> > If you can't tell, I'm pissed and as far as I'm concerned, rightly so. Again, we were told this issue was fixed. I spent weeks thinking I was running into vanilla bugs, trying to figure out a way to save my, so-I-thought, corrupting/dying world, only to find out it's all due to a dev that claimed their stuff was fixed then hid their head in the sand.
> 
> Again, give me any evidence that a dev claimed it is fixed. See, the issue report is **open**.
> 
> > When someone can give me the 100+ hours I spent fixing chunks, researching ways to stop this, trying different types of servers in hopes of using plugins to stop it... then I'll stop being pissed. Sound good?
> 
> 100+ hours? From what you have said before, there is no way you spent this long. I’m guessing 20 mins fixing it and 5 mins ranting on GitHub? Also, the devs are the ones spending hours. Remember that you are getting this for free. Just stop using the mods. Nobody cares. So what if your lack of common sense means you have to type a rant on GitHub? Deal with it. There are thousands of people using these mods, and these mods are being developed for free.
> 
> Don’t bother typing one of your “valuable” responses, it’s just spam at this point.

"This release fixes two critical bugs introduced in 0.7.0.

Bug Fixes
Fixed a game hangup that occured in some situations where chunks were resent due to large numbers of block updates or specific servers (#36, #39)
Fixed that some chunks were missing skylight after worldgen, due to wrong order of operations caused by a missing update notification. The fix will only prevent new glitches in chunks generated with 0.7.1 but will not repair already existing glitches. If upgrading an already corrupted world to 0.7.1, you need to erase the light cache once, see the note on MC-142134 for complete instructions."  

Last change log kid.  Maybe I don't have technical knowledge, but I do what I can.  And yes, 100+ hours when you, like me, don't know you can launch the server with a force update to clear the lighting, going around finding the chunks, going through caves, relighting them at my farms, etc...

The only words I have for you beyond this, are f off child. You can change your name, but you're still the same whining, crying, little JellySquid baby you've always been.  Keep up crying all over the net about your shit code. You're not being bullied if people are pointing out the truth.

**Comment by jellysquid3** [comment] 2021-04-13 18:10
@BBloom81 Disrupting our issue tracker to raise your grievances with a project given to you for free, without any strings attached, while our volunteers attempt to resolve the bug at hand, is not a productive use of anyone's time. Your attitude and tone is not welcomed nor helpful, and you have taken to giving the most uncharitable interpretation of our words at every opportunity. I will not be entertaining it any further.

At risk of stating the obvious, we _do_ care about issues, and we know that there are likely a few still lurking -- hence the reason the mods are still in their 0.x (alpha) series.  Some issues are inherently more complex to resolve than others, especially ones like this that involve deeply intricate and complex threading code. As a result we have to rely on user reports and confirmation to be absolutely certain a problem is resolved, and in this case, we left the issue open for that very reason.

**Comment by PhiProven** [comment] 2021-04-30 21:19
I call this one fixed in 0.7.2.
Please open a new report if some new glitches show up in 0.7.2.

**Closed as completed by PhiProven** 2021-04-30 21:19 UTC
